theme: minima

title: napari plugin Alfa Cohort
description: Materials related to the napari plugin Alfa Cohort collaboration

plugins:
  - jekyll-mentions
  - jemoji

header_pages:
  - README.md
  - projects/index.md
  - meetings/index.md
  - resources/index.md
